version: "2"
services:
  #Jackett
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Bogota
    volumes:
      - /home/docker/jackett/data:/config
      - /home/docker/jackett/blackhole:/downloads
    ports:
      - 9117:9117
    networks:
      - mediaServerNet
    restart: unless-stopped

  #Sonarr
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Bogota
    volumes:
      - /home/docker/sonarr/data:/config
      - /home/docker/common/media/tv:/tv
      - /home/docker/common/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - mediaServerNet
    restart: unless-stopped

  #Torrent
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Bogota
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /home/docker/qbittorrent/config:/config
      - /home/docker/common/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    networks:
      - mediaServerNet
    restart: unless-stopped

  #Plex
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_UID=0
      - PLEX_GID=0
      - TZ=America/Bogota 
      - PLEX_CLAIM=claim-cf8mTL79x7zAKh6L2jYr
      - ADVERTISE_IP=http://10.0.0.80:32400/
    hostname: homeserver
    volumes:
      - /home/docker/plex/database:/config
      - /home/docker/plex/transcode/temp:/transcode
      - /home/docker/common/media:/data
    networks:
      - mediaServerNet

  #Radarr
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Bogota
    volumes:
      - /home/docker/radarr/data:/config
      - /home/docker/common/media/movies:/movies
      - /home/docker/common/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - mediaServerNet
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Bogota
    volumes:
      - /home/docker/bazarr/config:/config
      - /home/docker/common/media/movies:/movies
      - /home/docker/common/media/tv:/tv
    ports:
      - 6767:6767
    networks:
      - mediaServerNet
    restart: unless-stopped

  homebridge:
    image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=America/Bogota
    volumes:
      - /home/homebridge:/homebridge



#network
networks:
  mediaServerNet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
